In [1]:
!pip install numpy-financial

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy-financial
  Downloading numpy_financial-1.0.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: numpy>=1.15 in c:\programdata\anaconda3\lib\site-packages (from numpy-financial) (1.26.4)
Downloading numpy_financial-1.0.0-py3-none-any.whl (14 kB)
Installing collected packages: numpy-financial
Successfully installed numpy-financial-1.0.0

In [16]:
# Import libraries
import xlwings as xw
import pandas as pd
import openpyxl
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

In [17]:
# Specify workbook and Sheet
file_name = "your_workbook.xlsx"
file_name = "31 Cash_Flow OWS (27 may 26) RIO SECO.xlsm"

# Load the workbook and select the sheet
wb = openpyxl.load_workbook(file_name, data_only=True)
sheet = wb["Case A"]

In [59]:
# Function to import range

def Import_Range_from_Excel(range_str,row_i):
    cell_range = sheet[range_str] # Define cell range (e.g., B2:E10)
    
    # Convert range to a pandas DataFrame
    data = []
    for row in cell_range: data.append([cell.value for cell in row])
    
    df = pd.DataFrame(data)
    
    # Optional: Set the first row as the header
    #df.columns = df.iloc[row_i]
    #df = df[1:].reset_index(drop=True)
    
    df.head()
    return df  # Optional

In [196]:
Prod_df = Import_Range_from_Excel("E10:AR17",0)
Prod_df

CAPEX_df = Import_Range_from_Excel("E97:AR97",0)
CAPEX_df

# Copy the first row
new_row = CAPEX_df.loc[0].copy()

# Append to DataFrame
Prod_df = pd.concat([Prod_df, new_row.to_frame().T], ignore_index=True)
Prod_df.index = ['year', 'Date', 'Days','BOEs','Gas Prod','Gas Sale','Oil','Gasoline','CAPEX']
Prod_df = Prod_df.transpose()
Prod_df

,year,Date,Days,BOEs,Gas Prod,Gas Sale,Oil,Gasoline,CAPEX
0,1,2026-01-01 00:00:00,365,280.786638,1.529167,1.406833,30.583333,7.645833,-10500000
1,2,2027-01-01 00:00:00,365,1652.586207,9,8.28,180,45,0
2,3,2028-01-01 00:00:00,366,1495.321837,8.143537,7.492054,162.870735,40.717684,0
3,4,2029-01-01 00:00:00,365,1224.265973,6.667364,6.133975,133.34728,33.33682,0
4,5,2030-01-01 00:00:00,365,906.95854,4.939305,4.54416,98.786094,24.696524,0
5,6,2031-01-01 00:00:00,365,607.95249,3.310915,3.046042,66.218299,16.554575,0
6,7,2032-01-01 00:00:00,366,368.741825,2.008171,1.847518,40.163429,10.040857,0
7,8,2033-01-01 00:00:00,365,202.369804,1.102108,1.013939,22.042157,5.510539,0
8,9,2034-01-01 00:00:00,365,100.493871,0.547291,0.503507,10.945811,2.736453,0
9,10,2035-01-01 00:00:00,365,45.154807,0.245914,0.22624,4.91827,1.229568,0
10,11,2036-01-01 00:00:00,366,18.358574,0.099981,0.091982,1.999619,0.499905,0
11,12,2037-01-01 00:00:00,365,0,None,None,None,None,0
12,13,2038-01-01 00:00:00,365,0,None,None,None,None,0
13,14,2039-01-01 00:00:00,365,0,None,None,None,None,0
14,15,2040-01-01 00:00:00,366,0,None,None,None,None,0
15,16,2041-01-01 00:00:00,365,0,None,None,None,None,0
16,17,2042-01-01 00:00:00,365,0,None,None,None,None,0
17,18,2043-01-01 00:00:00,365,0,None,None,None,None,0
18,19,2044-01-01 00:00:00,366,0,None,None,None,None,0
19,20,2045-01-01 00:00:00,365,0,None,None,None,None,0
20,21,2046-01-01 00:00:00,365,0,None,None,None,None,0
21,22,2047-01-01 00:00:00,365,0,None,None,None,None,0
22,23,2048-01-01 00:00:00,366,0,None,None,None,None,0
23,24,2049-01-01 00:00:00,365,0,None,None,None,None,0
24,25,2050-01-01 00:00:00,365,0,None,None,None,None,0
25,26,2051-01-01 00:00:00,365,0,None,None,None,None,0
26,27,2052-01-01 00:00:00,366,0,None,None,None,None,0
27,28,2053-01-01 00:00:00,365,0,None,None,None,None,0
28,29,2054-01-01 00:00:00,365,0,None,None,None,None,0
29,30,2055-01-01 00:00:00,365,0,None,None,None,None,0
30,31,2056-01-01 00:00:00,366,0,None,None,None,None,0
31,32,2057-01-01 00:00:00,365,0,None,None,None,None,0
32,33,2058-01-01 00:00:00,365,0,None,None,None,None,0
33,34,2059-01-01 00:00:00,365,0,None,None,None,None,0
34,35,2060-01-01 00:00:00,366,0,None,None,None,None,0
35,36,2061-01-01 00:00:00,365,0,None,None,None,None,0
36,37,2062-01-01 00:00:00,365,0,None,None,None,None,0
37,38,2063-01-01 00:00:00,365,0,None,None,None,None,0
38,39,2064-01-01 00:00:00,366,0,None,None,None,None,0
39,40,2065-01-01 00:00:00,365,0,None,None,None,None,0

In [197]:
Prod_df['Date'] = pd.to_datetime(Prod_df['Date'], format='%Y %m %d')
Prod_df

,year,Date,Days,BOEs,Gas Prod,Gas Sale,Oil,Gasoline,CAPEX
0,1,2026-01-01,365,280.786638,1.529167,1.406833,30.583333,7.645833,-10500000
1,2,2027-01-01,365,1652.586207,9,8.28,180,45,0
2,3,2028-01-01,366,1495.321837,8.143537,7.492054,162.870735,40.717684,0
3,4,2029-01-01,365,1224.265973,6.667364,6.133975,133.34728,33.33682,0
4,5,2030-01-01,365,906.95854,4.939305,4.54416,98.786094,24.696524,0
5,6,2031-01-01,365,607.95249,3.310915,3.046042,66.218299,16.554575,0
6,7,2032-01-01,366,368.741825,2.008171,1.847518,40.163429,10.040857,0
7,8,2033-01-01,365,202.369804,1.102108,1.013939,22.042157,5.510539,0
8,9,2034-01-01,365,100.493871,0.547291,0.503507,10.945811,2.736453,0
9,10,2035-01-01,365,45.154807,0.245914,0.22624,4.91827,1.229568,0
10,11,2036-01-01,366,18.358574,0.099981,0.091982,1.999619,0.499905,0
11,12,2037-01-01,365,0,None,None,None,None,0
12,13,2038-01-01,365,0,None,None,None,None,0
13,14,2039-01-01,365,0,None,None,None,None,0
14,15,2040-01-01,366,0,None,None,None,None,0
15,16,2041-01-01,365,0,None,None,None,None,0
16,17,2042-01-01,365,0,None,None,None,None,0
17,18,2043-01-01,365,0,None,None,None,None,0
18,19,2044-01-01,366,0,None,None,None,None,0
19,20,2045-01-01,365,0,None,None,None,None,0
20,21,2046-01-01,365,0,None,None,None,None,0
21,22,2047-01-01,365,0,None,None,None,None,0
22,23,2048-01-01,366,0,None,None,None,None,0
23,24,2049-01-01,365,0,None,None,None,None,0
24,25,2050-01-01,365,0,None,None,None,None,0
25,26,2051-01-01,365,0,None,None,None,None,0
26,27,2052-01-01,366,0,None,None,None,None,0
27,28,2053-01-01,365,0,None,None,None,None,0
28,29,2054-01-01,365,0,None,None,None,None,0
29,30,2055-01-01,365,0,None,None,None,None,0
30,31,2056-01-01,366,0,None,None,None,None,0
31,32,2057-01-01,365,0,None,None,None,None,0
32,33,2058-01-01,365,0,None,None,None,None,0
33,34,2059-01-01,365,0,None,None,None,None,0
34,35,2060-01-01,366,0,None,None,None,None,0
35,36,2061-01-01,365,0,None,None,None,None,0
36,37,2062-01-01,365,0,None,None,None,None,0
37,38,2063-01-01,365,0,None,None,None,None,0
38,39,2064-01-01,366,0,None,None,None,None,0
39,40,2065-01-01,365,0,None,None,None,None,0

In [198]:
# Delete rows without production

# Iterate from last row to first
element = 0
for index, row in Prod_df.iloc[::-1].iterrows():
    print(f"Index: {index}, Value: {row['BOEs']}")
    element = element + 1
    if row['BOEs'] >0:
        LR = index
        break  # Stops the loop completely
print(element)
element = element - 2
# Drops the last 2 rows
Prod_df = Prod_df.iloc[:-element]

Index: 39, Value: 0
Index: 38, Value: 0
Index: 37, Value: 0
Index: 36, Value: 0
Index: 35, Value: 0
Index: 34, Value: 0
Index: 33, Value: 0
Index: 32, Value: 0
Index: 31, Value: 0
Index: 30, Value: 0
Index: 29, Value: 0
Index: 28, Value: 0
Index: 27, Value: 0
Index: 26, Value: 0
Index: 25, Value: 0
Index: 24, Value: 0
Index: 23, Value: 0
Index: 22, Value: 0
Index: 21, Value: 0
Index: 20, Value: 0
Index: 19, Value: 0
Index: 18, Value: 0
Index: 17, Value: 0
Index: 16, Value: 0
Index: 15, Value: 0
Index: 14, Value: 0
Index: 13, Value: 0
Index: 12, Value: 0
Index: 11, Value: 0
Index: 10, Value: 18.358574451560777
30

In [202]:
Prod_df

,year,Date,Days,BOEs,Gas Prod,Gas Sale,Oil,Gasoline,CAPEX
0,1,2026-01-01,365,280.786638,1.529167,1.406833,30.583333,7.645833,-10500000
1,2,2027-01-01,365,1652.586207,9,8.28,180,45,0
2,3,2028-01-01,366,1495.321837,8.143537,7.492054,162.870735,40.717684,0
3,4,2029-01-01,365,1224.265973,6.667364,6.133975,133.34728,33.33682,0
4,5,2030-01-01,365,906.95854,4.939305,4.54416,98.786094,24.696524,0
5,6,2031-01-01,365,607.95249,3.310915,3.046042,66.218299,16.554575,0
6,7,2032-01-01,366,368.741825,2.008171,1.847518,40.163429,10.040857,0
7,8,2033-01-01,365,202.369804,1.102108,1.013939,22.042157,5.510539,0
8,9,2034-01-01,365,100.493871,0.547291,0.503507,10.945811,2.736453,0
9,10,2035-01-01,365,45.154807,0.245914,0.22624,4.91827,1.229568,0
10,11,2036-01-01,366,18.358574,0.099981,0.091982,1.999619,0.499905,0
11,12,2037-01-01,365,0,None,None,None,None,0

In [209]:
BTU_scf = sheet["D50"].value
display(BTU_scf)

USD_MMBTU = sheet["D51"].value
display(USD_MMBTU)

Oil_Price = sheet["D53"].value
display(Oil_Price)


Gov_tax = sheet["D88"].value
print('Government Tax = ', Gov_tax)

Company_Share = sheet["D109"].value
print('Company Share = ', Company_Share)


Cash_Flow_df = pd.DataFrame()
Cash_Flow_df = Prod_df.copy(deep=True)

Cash_Flow_df.loc[:, 'Gas Price'] = BTU_scf * USD_MMBTU
Cash_Flow_df.loc[:, 'Oil Price'] = Oil_Price

Cash_Flow_df.loc[:, 'Gas Rev'] = Cash_Flow_df['Gas Sale'] * Cash_Flow_df['Gas Price']
Cash_Flow_df.loc[:, 'Liquids Rev'] = (Cash_Flow_df['Oil']+Cash_Flow_df['Gasoline']) * Cash_Flow_df['Oil Price']

Cash_Flow_df.loc[:, 'Total Rev USD_day'] = Cash_Flow_df['Gas Rev']+Cash_Flow_df['Liquids Rev']
Cash_Flow_df.loc[:, 'Total Revenue year'] = Cash_Flow_df['Total Rev USD_day'] * Cash_Flow_df['Days']
Cash_Flow_df.loc[:, 'Company Revenue'] = Cash_Flow_df['Total Revenue year'] * Gov_tax

Cash_Flow_df

1020

5.68

65

Government Tax =  0.5
Government Tax =  0.5

,year,Date,Days,BOEs,Gas Prod,Gas Sale,Oil,Gasoline,CAPEX,Gas Price,Oil Price,Gas Rev,Liquids Rev,Total Rev USD_day,Total Revenue year,Company Revenue
0,1,2026-01-01,365,280.786638,1.529167,1.406833,30.583333,7.645833,-10500000,5793.6,65,8150.6296,2484.895833,10635.525433,3881966.783167,1940983.391583
1,2,2027-01-01,365,1652.586207,9,8.28,180,45,0,5793.6,65,47971.008,14625,62596.008,22847542.92,11423771.46
2,3,2028-01-01,366,1495.321837,8.143537,7.492054,162.870735,40.717684,0,5793.6,65,43405.963019,13233.247239,56639.210258,20729950.954457,10364975.477228
3,4,2029-01-01,365,1224.265973,6.667364,6.133975,133.34728,33.33682,0,5793.6,65,35537.796791,10834.466477,46372.263268,16925876.092944,8462938.046472
4,5,2030-01-01,365,906.95854,4.939305,4.54416,98.786094,24.696524,0,5793.6,65,26327.047386,8026.370178,34353.417563,12538997.410654,6269498.705327
5,6,2031-01-01,365,607.95249,3.310915,3.046042,66.218299,16.554575,0,5793.6,65,17647.547615,5380.236827,23027.784443,8405141.32155,4202570.660775
6,7,2032-01-01,366,368.741825,2.008171,1.847518,40.163429,10.040857,0,5793.6,65,10703.778698,3263.278592,13967.05729,5111942.968027,2555971.484014
7,8,2033-01-01,365,202.369804,1.102108,1.013939,22.042157,5.510539,0,5793.6,65,5874.358299,1790.925263,7665.283563,2797828.50034,1398914.25017
8,9,2034-01-01,365,100.493871,0.547291,0.503507,10.945811,2.736453,0,5793.6,65,2917.120001,889.347166,3806.467167,1389360.515798,694680.257899
9,10,2035-01-01,365,45.154807,0.245914,0.22624,4.91827,1.229568,0,5793.6,65,1310.746508,399.609441,1710.355949,624279.921349,312139.960674
10,11,2036-01-01,366,18.358574,0.099981,0.091982,1.999619,0.499905,0,5793.6,65,532.909762,162.469074,695.378836,254508.654042,127254.327021
11,12,2037-01-01,365,0,None,None,None,None,0,5793.6,65,NaN,NaN,NaN,NaN,NaN

In [183]:
Cash_Flow_df = pd.DataFrame()

In [205]:
Cash_Flow_df
#Prod_df

,year,Date,Days,BOEs,Gas Prod,Gas Sale,Oil,Gasoline,CAPEX,Gas Price,Oil Price,Gas Rev,Liquids Rev,Total Rev USD_day
0,1,2026-01-01,365,280.786638,1.529167,1.406833,30.583333,7.645833,-10500000,5793.6,65,8150.6296,2484.895833,10635.525433
1,2,2027-01-01,365,1652.586207,9,8.28,180,45,0,5793.6,65,47971.008,14625,62596.008
2,3,2028-01-01,366,1495.321837,8.143537,7.492054,162.870735,40.717684,0,5793.6,65,43405.963019,13233.247239,56639.210258
3,4,2029-01-01,365,1224.265973,6.667364,6.133975,133.34728,33.33682,0,5793.6,65,35537.796791,10834.466477,46372.263268
4,5,2030-01-01,365,906.95854,4.939305,4.54416,98.786094,24.696524,0,5793.6,65,26327.047386,8026.370178,34353.417563
5,6,2031-01-01,365,607.95249,3.310915,3.046042,66.218299,16.554575,0,5793.6,65,17647.547615,5380.236827,23027.784443
6,7,2032-01-01,366,368.741825,2.008171,1.847518,40.163429,10.040857,0,5793.6,65,10703.778698,3263.278592,13967.05729
7,8,2033-01-01,365,202.369804,1.102108,1.013939,22.042157,5.510539,0,5793.6,65,5874.358299,1790.925263,7665.283563
8,9,2034-01-01,365,100.493871,0.547291,0.503507,10.945811,2.736453,0,5793.6,65,2917.120001,889.347166,3806.467167
9,10,2035-01-01,365,45.154807,0.245914,0.22624,4.91827,1.229568,0,5793.6,65,1310.746508,399.609441,1710.355949
10,11,2036-01-01,366,18.358574,0.099981,0.091982,1.999619,0.499905,0,5793.6,65,532.909762,162.469074,695.378836
11,12,2037-01-01,365,0,None,None,None,None,0,5793.6,65,NaN,NaN,NaN

In [2]:
import numpy_financial as npf

# 1. Define your financial parameters
discount_rate = 0.10  # 10% cost of capital
cash_flows = [-100000, 30000, 40000, 50000, 60000]  # Year 0 to Year 4

# 2. Compute the NPV
# The function automatically treats cash_flows[0] as Year 0 (undiscounted)
npv_result = npf.npv(discount_rate, cash_flows)

# 3. Display the formatted result
print(f"Project NPV: ${npv_result:,.2f}")

Project NPV: $38,877.13